//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.05 at 09:49:12 AM CET 
//


package rechnerAufgabe4.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{genericNamespace}ort"/>
 *         &lt;element ref="{genericNamespace}postleihzahl"/>
 *         &lt;element ref="{genericNamespace}strasze"/>
 *         &lt;element ref="{genericNamespace}haus-nummer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ort",
    "postleihzahl",
    "strasze",
    "hausNummer"
})
@XmlRootElement(name = "adresse")
public class Adresse {

    @XmlElement(required = true)
    protected String ort;
    @XmlElement(required = true)
    protected String postleihzahl;
    @XmlElement(required = true)
    protected String strasze;
    @XmlElement(name = "haus-nummer", required = true)
    protected String hausNummer;

    /**
     * Gets the value of the ort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrt() {
        return ort;
    }

    /**
     * Sets the value of the ort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrt(String value) {
        this.ort = value;
    }

    /**
     * Gets the value of the postleihzahl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPostleihzahl() {
        return postleihzahl;
    }

    /**
     * Sets the value of the postleihzahl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPostleihzahl(String value) {
        this.postleihzahl = value;
    }

    /**
     * Gets the value of the strasze property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStrasze() {
        return strasze;
    }

    /**
     * Sets the value of the strasze property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStrasze(String value) {
        this.strasze = value;
    }

    /**
     * Gets the value of the hausNummer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHausNummer() {
        return hausNummer;
    }

    /**
     * Sets the value of the hausNummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHausNummer(String value) {
        this.hausNummer = value;
    }

}
