//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.04 at 09:23:54 PM CET 
//


package rechnerAufgabe4.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{genericNamespace}name-unternehmen"/>
 *         &lt;element ref="{genericNamespace}email-adresse" minOccurs="0"/>
 *         &lt;element ref="{genericNamespace}adresse"/>
 *         &lt;element ref="{genericNamespace}telefon-nummer" minOccurs="0"/>
 *         &lt;element ref="{genericNamespace}fax-nummer" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nameUnternehmen",
    "emailAdresse",
    "adresse",
    "telefonNummer",
    "faxNummer"
})
@XmlRootElement(name = "anschrift-des-leistenden-unternehmers")
public class AnschriftDesLeistendenUnternehmers {

    @XmlElement(name = "name-unternehmen", required = true)
    protected String nameUnternehmen;
    @XmlElement(name = "email-adresse")
    protected String emailAdresse;
    @XmlElement(required = true)
    protected Adresse adresse;
    @XmlElement(name = "telefon-nummer")
    protected BigDecimal telefonNummer;
    @XmlElement(name = "fax-nummer")
    protected BigDecimal faxNummer;

    /**
     * Gets the value of the nameUnternehmen property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameUnternehmen() {
        return nameUnternehmen;
    }

    /**
     * Sets the value of the nameUnternehmen property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameUnternehmen(String value) {
        this.nameUnternehmen = value;
    }

    /**
     * Gets the value of the emailAdresse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAdresse() {
        return emailAdresse;
    }

    /**
     * Sets the value of the emailAdresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAdresse(String value) {
        this.emailAdresse = value;
    }

    /**
     * Gets the value of the adresse property.
     * 
     * @return
     *     possible object is
     *     {@link Adresse }
     *     
     */
    public Adresse getAdresse() {
        return adresse;
    }

    /**
     * Sets the value of the adresse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Adresse }
     *     
     */
    public void setAdresse(Adresse value) {
        this.adresse = value;
    }

    /**
     * Gets the value of the telefonNummer property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTelefonNummer() {
        return telefonNummer;
    }

    /**
     * Sets the value of the telefonNummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTelefonNummer(BigDecimal value) {
        this.telefonNummer = value;
    }

    /**
     * Gets the value of the faxNummer property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getFaxNummer() {
        return faxNummer;
    }

    /**
     * Sets the value of the faxNummer property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setFaxNummer(BigDecimal value) {
        this.faxNummer = value;
    }

}
