//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.04 at 09:23:54 PM CET 
//


package rechnerAufgabe4.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{genericNamespace}bankverbindung" minOccurs="0"/>
 *         &lt;element ref="{genericNamespace}bitcoin" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "bezahl-moeglichkeiten")
public class BezahlMoeglichkeiten {

    protected Bankverbindung bankverbindung;
    protected String bitcoin;

    /**
     * Gets the value of the bankverbindung property.
     * 
     * @return
     *     possible object is
     *     {@link Bankverbindung }
     *     
     */
    public Bankverbindung getBankverbindung() {
        return bankverbindung;
    }

    /**
     * Sets the value of the bankverbindung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Bankverbindung }
     *     
     */
    public void setBankverbindung(Bankverbindung value) {
        this.bankverbindung = value;
    }

    /**
     * Gets the value of the bitcoin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBitcoin() {
        return bitcoin;
    }

    /**
     * Sets the value of the bitcoin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBitcoin(String value) {
        this.bitcoin = value;
    }

}
