//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.05 at 09:49:12 AM CET 
//


package rechnerAufgabe4.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{genericNamespace}bezeichnung"/>
 *         &lt;element ref="{genericNamespace}mengen-anzahl" minOccurs="0"/>
 *         &lt;element ref="{genericNamespace}mengen-bezeichnung" minOccurs="0"/>
 *         &lt;element ref="{genericNamespace}einzel-preis" minOccurs="0"/>
 *         &lt;element ref="{genericNamespace}gesamt-preis"/>
 *         &lt;element ref="{genericNamespace}mehrwertsteuer-in-prozent"/>
 *         &lt;element ref="{genericNamespace}datum" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="position" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "bezeichnung",
    "mengenAnzahl",
    "mengenBezeichnung",
    "einzelPreis",
    "gesamtPreis",
    "mehrwertsteuerInProzent",
    "datum"
})
@XmlRootElement(name = "leistung")
public class Leistung {

    @XmlElement(required = true)
    protected String bezeichnung;
    @XmlElement(name = "mengen-anzahl")
    protected BigDecimal mengenAnzahl;
    @XmlElement(name = "mengen-bezeichnung")
    protected String mengenBezeichnung;
    @XmlElement(name = "einzel-preis")
    protected BigDecimal einzelPreis;
    @XmlElement(name = "gesamt-preis", required = true)
    protected BigDecimal gesamtPreis;
    @XmlElement(name = "mehrwertsteuer-in-prozent", required = true)
    protected BigDecimal mehrwertsteuerInProzent;
    protected Datum datum;
    @XmlAttribute(name = "position")
    @XmlSchemaType(name = "anySimpleType")
    protected String position;

    /**
     * Gets the value of the bezeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBezeichnung() {
        return bezeichnung;
    }

    /**
     * Sets the value of the bezeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBezeichnung(String value) {
        this.bezeichnung = value;
    }

    /**
     * Gets the value of the mengenAnzahl property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMengenAnzahl() {
        return mengenAnzahl;
    }

    /**
     * Sets the value of the mengenAnzahl property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMengenAnzahl(BigDecimal value) {
        this.mengenAnzahl = value;
    }

    /**
     * Gets the value of the mengenBezeichnung property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMengenBezeichnung() {
        return mengenBezeichnung;
    }

    /**
     * Sets the value of the mengenBezeichnung property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMengenBezeichnung(String value) {
        this.mengenBezeichnung = value;
    }

    /**
     * Gets the value of the einzelPreis property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEinzelPreis() {
        return einzelPreis;
    }

    /**
     * Sets the value of the einzelPreis property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEinzelPreis(BigDecimal value) {
        this.einzelPreis = value;
    }

    /**
     * Gets the value of the gesamtPreis property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGesamtPreis() {
        return gesamtPreis;
    }

    /**
     * Sets the value of the gesamtPreis property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGesamtPreis(BigDecimal value) {
        this.gesamtPreis = value;
    }

    /**
     * Gets the value of the mehrwertsteuerInProzent property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMehrwertsteuerInProzent() {
        return mehrwertsteuerInProzent;
    }

    /**
     * Sets the value of the mehrwertsteuerInProzent property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMehrwertsteuerInProzent(BigDecimal value) {
        this.mehrwertsteuerInProzent = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link Datum }
     *     
     */
    public Datum getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Datum }
     *     
     */
    public void setDatum(Datum value) {
        this.datum = value;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosition(String value) {
        this.position = value;
    }

}
