//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.05 at 09:49:12 AM CET 
//


package rechnerAufgabe4.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rechnerAufgabe4.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GesamtBetrag_QNAME = new QName("genericNamespace", "gesamt-betrag");
    private final static QName _Bezeichnung_QNAME = new QName("genericNamespace", "bezeichnung");
    private final static QName _EinzelPreis_QNAME = new QName("genericNamespace", "einzel-preis");
    private final static QName _Vorname_QNAME = new QName("genericNamespace", "vorname");
    private final static QName _Anrede_QNAME = new QName("genericNamespace", "anrede");
    private final static QName _RechnungsNummer_QNAME = new QName("genericNamespace", "rechnungs-nummer");
    private final static QName _MehrwertsteuerInProzent_QNAME = new QName("genericNamespace", "mehrwertsteuer-in-prozent");
    private final static QName _MengenBezeichnung_QNAME = new QName("genericNamespace", "mengen-bezeichnung");
    private final static QName _GesamtPreis_QNAME = new QName("genericNamespace", "gesamt-preis");
    private final static QName _Jahr_QNAME = new QName("genericNamespace", "jahr");
    private final static QName _KontoNr_QNAME = new QName("genericNamespace", "konto-nr");
    private final static QName _Ort_QNAME = new QName("genericNamespace", "ort");
    private final static QName _Blz_QNAME = new QName("genericNamespace", "blz");
    private final static QName _HausNummer_QNAME = new QName("genericNamespace", "haus-nummer");
    private final static QName _Postleihzahl_QNAME = new QName("genericNamespace", "postleihzahl");
    private final static QName _Iban_QNAME = new QName("genericNamespace", "iban");
    private final static QName _Nachname_QNAME = new QName("genericNamespace", "nachname");
    private final static QName _MengenAnzahl_QNAME = new QName("genericNamespace", "mengen-anzahl");
    private final static QName _Bic_QNAME = new QName("genericNamespace", "bic");
    private final static QName _Bitcoin_QNAME = new QName("genericNamespace", "bitcoin");
    private final static QName _UmsatzsteuerIdentifikationsNummer_QNAME = new QName("genericNamespace", "umsatzsteuer-identifikations-nummer");
    private final static QName _MehrwertSteuerBetrag_QNAME = new QName("genericNamespace", "mehrwert-steuer-betrag");
    private final static QName _NettoBetrag_QNAME = new QName("genericNamespace", "netto-betrag");
    private final static QName _Monat_QNAME = new QName("genericNamespace", "monat");
    private final static QName _FaxNummer_QNAME = new QName("genericNamespace", "fax-nummer");
    private final static QName _Bank_QNAME = new QName("genericNamespace", "bank");
    private final static QName _VerwendeteWaehrung_QNAME = new QName("genericNamespace", "verwendete-waehrung");
    private final static QName _EmailAdresse_QNAME = new QName("genericNamespace", "email-adresse");
    private final static QName _TelefonNummer_QNAME = new QName("genericNamespace", "telefon-nummer");
    private final static QName _SteuerNummerDesLeistendenUnternehmers_QNAME = new QName("genericNamespace", "steuer-nummer-des-leistenden-unternehmers");
    private final static QName _Tag_QNAME = new QName("genericNamespace", "tag");
    private final static QName _Strasze_QNAME = new QName("genericNamespace", "strasze");
    private final static QName _NameUnternehmen_QNAME = new QName("genericNamespace", "name-unternehmen");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rechnerAufgabe4.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Datum }
     * 
     */
    public Datum createDatum() {
        return new Datum();
    }

    /**
     * Create an instance of {@link BezahlMoeglichkeiten }
     * 
     */
    public BezahlMoeglichkeiten createBezahlMoeglichkeiten() {
        return new BezahlMoeglichkeiten();
    }

    /**
     * Create an instance of {@link Bankverbindung }
     * 
     */
    public Bankverbindung createBankverbindung() {
        return new Bankverbindung();
    }

    /**
     * Create an instance of {@link Entgelt }
     * 
     */
    public Entgelt createEntgelt() {
        return new Entgelt();
    }

    /**
     * Create an instance of {@link Leistung }
     * 
     */
    public Leistung createLeistung() {
        return new Leistung();
    }

    /**
     * Create an instance of {@link Leistungen }
     * 
     */
    public Leistungen createLeistungen() {
        return new Leistungen();
    }

    /**
     * Create an instance of {@link Rechnung }
     * 
     */
    public Rechnung createRechnung() {
        return new Rechnung();
    }

    /**
     * Create an instance of {@link AnschriftDesLeistendenUnternehmers }
     * 
     */
    public AnschriftDesLeistendenUnternehmers createAnschriftDesLeistendenUnternehmers() {
        return new AnschriftDesLeistendenUnternehmers();
    }

    /**
     * Create an instance of {@link Adresse }
     * 
     */
    public Adresse createAdresse() {
        return new Adresse();
    }

    /**
     * Create an instance of {@link AnschriftDesLeistungsEmpfaengers }
     * 
     */
    public AnschriftDesLeistungsEmpfaengers createAnschriftDesLeistungsEmpfaengers() {
        return new AnschriftDesLeistungsEmpfaengers();
    }

    /**
     * Create an instance of {@link NameLeistungsEmpfaenger }
     * 
     */
    public NameLeistungsEmpfaenger createNameLeistungsEmpfaenger() {
        return new NameLeistungsEmpfaenger();
    }

    /**
     * Create an instance of {@link AustellungsDatum }
     * 
     */
    public AustellungsDatum createAustellungsDatum() {
        return new AustellungsDatum();
    }

    /**
     * Create an instance of {@link Rechnungen }
     * 
     */
    public Rechnungen createRechnungen() {
        return new Rechnungen();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "gesamt-betrag")
    public JAXBElement<BigDecimal> createGesamtBetrag(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_GesamtBetrag_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "bezeichnung")
    public JAXBElement<String> createBezeichnung(String value) {
        return new JAXBElement<String>(_Bezeichnung_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "einzel-preis")
    public JAXBElement<BigDecimal> createEinzelPreis(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_EinzelPreis_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "vorname")
    public JAXBElement<String> createVorname(String value) {
        return new JAXBElement<String>(_Vorname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "anrede")
    public JAXBElement<String> createAnrede(String value) {
        return new JAXBElement<String>(_Anrede_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "rechnungs-nummer")
    public JAXBElement<String> createRechnungsNummer(String value) {
        return new JAXBElement<String>(_RechnungsNummer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "mehrwertsteuer-in-prozent")
    public JAXBElement<BigDecimal> createMehrwertsteuerInProzent(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_MehrwertsteuerInProzent_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "mengen-bezeichnung")
    public JAXBElement<String> createMengenBezeichnung(String value) {
        return new JAXBElement<String>(_MengenBezeichnung_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "gesamt-preis")
    public JAXBElement<BigDecimal> createGesamtPreis(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_GesamtPreis_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "jahr")
    public JAXBElement<BigDecimal> createJahr(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Jahr_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "konto-nr")
    public JAXBElement<BigDecimal> createKontoNr(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_KontoNr_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "ort")
    public JAXBElement<String> createOrt(String value) {
        return new JAXBElement<String>(_Ort_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "blz")
    public JAXBElement<String> createBlz(String value) {
        return new JAXBElement<String>(_Blz_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "haus-nummer")
    public JAXBElement<String> createHausNummer(String value) {
        return new JAXBElement<String>(_HausNummer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "postleihzahl")
    public JAXBElement<String> createPostleihzahl(String value) {
        return new JAXBElement<String>(_Postleihzahl_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "iban")
    public JAXBElement<String> createIban(String value) {
        return new JAXBElement<String>(_Iban_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "nachname")
    public JAXBElement<String> createNachname(String value) {
        return new JAXBElement<String>(_Nachname_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "mengen-anzahl")
    public JAXBElement<BigDecimal> createMengenAnzahl(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_MengenAnzahl_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "bic")
    public JAXBElement<String> createBic(String value) {
        return new JAXBElement<String>(_Bic_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "bitcoin")
    public JAXBElement<String> createBitcoin(String value) {
        return new JAXBElement<String>(_Bitcoin_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "umsatzsteuer-identifikations-nummer")
    public JAXBElement<String> createUmsatzsteuerIdentifikationsNummer(String value) {
        return new JAXBElement<String>(_UmsatzsteuerIdentifikationsNummer_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "mehrwert-steuer-betrag")
    public JAXBElement<BigDecimal> createMehrwertSteuerBetrag(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_MehrwertSteuerBetrag_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "netto-betrag")
    public JAXBElement<BigDecimal> createNettoBetrag(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_NettoBetrag_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "monat")
    public JAXBElement<BigDecimal> createMonat(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Monat_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "fax-nummer")
    public JAXBElement<BigDecimal> createFaxNummer(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_FaxNummer_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "bank")
    public JAXBElement<String> createBank(String value) {
        return new JAXBElement<String>(_Bank_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "verwendete-waehrung")
    public JAXBElement<String> createVerwendeteWaehrung(String value) {
        return new JAXBElement<String>(_VerwendeteWaehrung_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "email-adresse")
    public JAXBElement<String> createEmailAdresse(String value) {
        return new JAXBElement<String>(_EmailAdresse_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "telefon-nummer")
    public JAXBElement<BigDecimal> createTelefonNummer(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_TelefonNummer_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "steuer-nummer-des-leistenden-unternehmers")
    public JAXBElement<BigDecimal> createSteuerNummerDesLeistendenUnternehmers(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_SteuerNummerDesLeistendenUnternehmers_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "tag")
    public JAXBElement<BigDecimal> createTag(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_Tag_QNAME, BigDecimal.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "strasze")
    public JAXBElement<String> createStrasze(String value) {
        return new JAXBElement<String>(_Strasze_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "genericNamespace", name = "name-unternehmen")
    public JAXBElement<String> createNameUnternehmen(String value) {
        return new JAXBElement<String>(_NameUnternehmen_QNAME, String.class, null, value);
    }

}
